
import { Banner } from "@/widgets/Banner";
import { Employees } from "@/widgets/Employees";
import { Interior } from "@/widgets/Interior";
import { Map } from "@/widgets/Map";
import { PriceList } from "@/widgets/PriceList";
import { PromotionsCertificates } from "@/widgets/PromotionsCertificates";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <Banner/>
    <PromotionsCertificates/>
    <PriceList/>
    <Interior/>
    <Employees/>
    <Map/>
    </>
  );
}
