services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_news
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass


  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    depends_on:
      - backend

  nextjs:
    build:
      context: ./frontend
    container_name: nextjs
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
