services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://your_db_user:your_db_password@db:5432/your_db_name
      env: backend/.env
      STATIC_URL: /static/
      STATIC_ROOT: /app/backend/staticfiles

  nginx:
    build:
      context: ./infra
      dockerfile: Dockerfile.nginx
    volumes:
      # - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/staticfiles:/app/backend/staticfiles
      - ./backend/media:/app/backend/media
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
