# Generated by Django 5.1.4 on 2025-02-16 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sale_photo', models.ImageField(blank=True, null=True, upload_to='sales/', verbose_name='Фото для акции')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст акции')),
                ('new_price', models.IntegerField(verbose_name='Новая цена')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='services.category')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price_min', models.IntegerField(verbose_name='Цена от')),
                ('price_max', models.IntegerField(verbose_name='Цена до')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('comment', models.CharField(max_length=255, verbose_name='Описание')),
                ('duration', models.IntegerField(verbose_name='Длительность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.category')),
            ],
        ),
    ]
