# Generated by Django 5.1.4 on 2025-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Имя-фамилия сотрудника')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя сотрудника')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия сотрудника')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество сотрудника')),
                ('specialization', models.CharField(max_length=50, verbose_name='Профессия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фотография сотрудника')),
                ('career_start_year', models.IntegerField(verbose_name='Год начала карьеры')),
            ],
        ),
    ]
